name: Release proton-ge-solosaravanan

on:
  release:
    types:
      - published

permissions:
  contents: write

concurrency:
  group: proton-ge-solosaravanan-${{ github.event.release.tag_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build release
    uses: ./.github/workflows/_job_build.yml
    with:
      name: ${{ github.event.release.tag_name }}

  upload:
    name: Upload release files
    needs:
      - build
    uses: ./.github/workflows/_job_upload.yml
    with:
      version: ${{ github.event.release.tag_name }}
      name: ${{ github.event.release.tag_name }}
